Fix "originalKeywordKind has been deprecated" error when deploying to Vercel
Full error message:
Error: Parsing error: DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer be used. Use 'identifierToKeywordKind(identifier)' instead.

This was caused by updating TypeScript to v5. Installing @typescript-eslint/eslint-plugin and @typescript-eslint/parser fixed the error.